# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e81026556515b6f351fed17cc833e6dd6a225d3a112286783b0f336eab44a8265a5f0454a6bbbd91136c2890a1b44bd4b32f4b00df64ed5938589fe3cd99762d

test:
  secret_key_base: 3c1bc80f547971097b7f0c99963a350f9275d6e14aced3d374d12ea1c677ff11fb7db23221f58af594ca364b90fd0d7a09e42ae433f1435e3bde4ab5df1e6ee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
